steps:
  - name: node:22
    args:
      - install
    dir: blog/next-blog
    entrypoint: npm
  - name: node:22
    args:
      - run
      - build
    dir: blog/next-blog
    entrypoint: npm
  - name: gcr.io/cloud-builders/gsutil
    args:
      - cp
      - '-r'
      - blog/next-blog/out/*
      - 'gs://$_MY_BUCKET/'
