identifier: k1y080scve7441df
appPort: 1864
staticPort: 1668
reloadPort: 2667
hostName: localhost
projectName: blog
homeFolder: C:\Users\Anshuman Kumar\Documents\GitHub\myblog
distFolder: dist/blog
outDir: C:\Users\Anshuman Kumar\Documents\GitHub\myblog\dist\static
handle404: ''
allowErrorCollect: false
