identifier: k1y080scve7441df
appPort: 1864
staticPort: 1668
reloadPort: 2667
hostName: localhost
projectName: blog
homeFolder: /home/anshuman/repos/angular-practice/my-blog/myblog
distFolder: dist/blog
outDir: /home/anshuman/repos/angular-practice/my-blog/myblog/dist/static
handle404: ''
allowErrorCollect: false
